//
//  MahdiPresenter.swift
//  VIPLearning
//
//  Created by Mahdi Saedi on 29/01/2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol MahdiPresentationLogic {
    
}

class MahdiPresenter: MahdiPresentationLogic {
    // MARK: - Properties
    private weak var viewController: MahdiDisplayLogic?
    init(viewController: MahdiDisplayLogic) {
        self.viewController = viewController
    }
}
