//
//  MahdiConfigurator.swift
//  VIPLearning
//
//  Created by Mahdi Saedi on 29/01/2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol MahdiConfigurator {
    func configure() -> MahdiViewController
}

final class MahdiDefaultConfigurator {
    private var sceneFactory: SceneFactory
    init(sceneFactory: SceneFactory) {
        self.sceneFactory = sceneFactory
    }
}

extension MahdiDefaultConfigurator: MahdiConfigurator {
    
    @discardableResult
    func configure() -> MahdiViewController {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let viewController: MahdiViewController = storyboard.instantiateViewController(withIdentifier: "MahdiViewController") as! MahdiViewController
        let worker = MahdiWorker()
        let interactor = MahdiInteractor()
        let presenter = MahdiPresenter(viewController: viewController)
        let router = MahdiRouter(sceneFactory: sceneFactory, viewController: viewController)
        
        router.dataStore = interactor
        interactor.presenter = presenter
        interactor.worker = worker
        viewController.interactor = interactor
        viewController.router = router
        
        return viewController
    }
}

