//
//  MahdiModels.swift
//  VIPLearning
//
//  Created by Mahdi Saedi on 29/01/2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

enum MahdiModels {
    // MARK: - Use Cases
    enum SomeUseCase {
        struct Request {
            
        }

        struct Response {
            
        }

        struct ViewModel {
        
        }
    }
}
