//
//  MahdiViewController.swift
//  VIPLearning
//
//  Created by Mahdi Saedi on 29/01/2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol MahdiDisplayLogic: AnyObject {
    
}

class MahdiViewController: UIViewController {
    var interactor: (MahdiBusinessLogic & MahdiDataStore)?
    var router: MahdiRoutingLogic?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupView()
    }
    
}

// MARK: - Display Logic Functions
extension MahdiViewController: MahdiDisplayLogic {
    
}

// MARK: - Private Functions
extension MahdiViewController {
    private func setupView() {
        
    }
}
