//
//  MahdiWorker.swift
//  VIPLearning
//
//  Created by Mahdi Saedi on 29/01/2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol MahdiWorkerLogic {
    
}

class MahdiWorker: MahdiWorkerLogic {
     let service: NetworkProtocol
    
     init(service: NetworkProtocol) {
         self.service = service
     }

    // MARK: - Methods

}
