//
//  AremWorker.swift
//  VIPLearning
//
//  Created by Alireza on 11/9/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol AremWorkerLogic {
    func getData() -> aremDatas
}

class AremWorker: AremWorkerLogic {
     let service: NetworkProtocol
    
     init(service: NetworkProtocol) {
         self.service = service
     }

    // MARK: - Methods
    func getData() -> aremDatas {
        service.createDataFromJson(with: "data")
    }

}
