//
//  AremConfigurator.swift
//  VIPLearning
//
//  Created by Alireza on 11/9/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import Foundation

protocol AremConfigurator {
    func configure(_ vc: AremViewController) -> AremViewController
}

final class AremDefaultConfigurator {
    private var sceneFactory: SceneFactory
    init(sceneFactory: SceneFactory) {
        self.sceneFactory = sceneFactory
    }
}

extension AremDefaultConfigurator: AremConfigurator {
    @discardableResult
    func configure(_ vc: AremViewController) -> AremViewController {
        sceneFactory.someConfigurator = self
        let service: SomeNetworkServiceProtocol = SomeNetworkService()
        let worker = AremWorker()
        let interactor = AremInteractor()
        let presenter = AremPresenter()
        let router = AremRouter()
        
        router.viewController = vc
        router.dataStore = interactor
        presenter.viewController = vc
        interactor.presenter = presenter
        interactor.worker = worker
        vc.interactor = interactor
        vc.router = router
        
        return vc
    }
}
