//
//  AremModels.swift
//  VIPLearning
//
//  Created by Alireza on 11/9/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

enum AremModels {
    // MARK: - Use Cases
    enum SomeUseCase {
        struct Request {
            
        }

        struct Response {
            
        }

        struct ViewModel {
        
        }
    }
}
