//
//  AremInteractor.swift
//  VIPLearning
//
//  Created by Alireza on 11/9/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol AremBusinessLogic {

}

protocol AremDataStore {
    func getDataFromJson()
}

class AremInteractor: AremBusinessLogic, AremDataStore {
    // MARK: - Properties
    var presenter: AremPresentationLogic?
    var worker: AremWorkerLogic?
    
    func getDataFromJson(){
        guard let data = worker?.getData() else { fatalError("No data")}
        presenter?.getPersonName(data: data)
    }
}
