//
//  AremWorker.swift
//  VIPLearning
//
//  Created by Alireza on 11/9/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol AremWorkerLogic {
    
}

class AremWorker: AremWorkerLogic {
     let service: SomeNetworkServiceProtocol
    
     init(service: SomeNetworkServiceProtocol) {
         self.service = service
     }

    // MARK: - Methods

}
