//
//  AremViewController.swift
//  VIPLearning
//
//  Created by Alireza on 11/9/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol AremDisplayLogic: AnyObject {
    
}

class AremViewController: UIViewController {
    var interactor: (AremBusinessLogic & AremDataStore)?
    var router: AremRoutingLogic?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupView()
    }
}

// MARK: - Display Logic Functions
extension AremViewController: AremDisplayLogic {
    
}

// MARK: - Private Functions
extension AremViewController {
    private func setupView() {
        
    }
}
