//
//  AremConfigurator.swift
//  VIPLearning
//
//  Created by Alireza on 11/9/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import Foundation
import UIKit.UIViewController

protocol FirstConfigurator {
    func configure() -> FirstViewController
}

final class FirstDefaultConfigurator {
    private var sceneFactory: SceneFactory
    private var service: NetworkProtocol
    init(sceneFactory: SceneFactory,service: NetworkProtocol) {
        self.sceneFactory = sceneFactory
        self.service = service
    }
}

extension FirstDefaultConfigurator: FirstConfigurator {
    func configure() -> FirstViewController {
        let viewController = UIStoryboard(name: "First", bundle: nil).instantiateViewController(withIdentifier: "FirstViewController") as! FirstViewController
        let worker = FirstWorker(service: service)
        let interactor = FirstInteractor()
        let presenter = FirstPresenter(viewController: viewController)
        let router = FirstRouter(sceneFactory: sceneFactory, viewController: viewController)
        
        interactor.presenter = presenter
        interactor.worker = worker
        viewController.interactor = interactor
        viewController.router = router
        
        return viewController
    }
}
