//
//  AremViewController.swift
//  VIPLearning
//
//  Created by Alireza on 11/9/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol FirstDisplayLogic: AnyObject {
    func showNextName(viewModel: FirstViewModel, data: FirstModel)
    func showDetail(viewModel: ViewModel)
}

class FirstViewController: UIViewController {
    var interactor: (FirstBusinessLogic & FirstDataStore)?
    var router: FirstRoutingLogic?
        
    @IBOutlet weak var detailButton: UIButton!
    @IBOutlet weak var actButton: UIButton!
    @IBOutlet weak var TitleLabel: UILabel!
    @IBAction func actButonAction(_ sender: Any) {
       interactor?.getDataFromJson()
    }
    
    @IBAction func detailButtonAction(_ sender: Any) {
        interactor?.getRoutingData()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupView()
    }
}

// MARK: - Display Logic Functions
extension FirstViewController: FirstDisplayLogic {
    func showNextName(viewModel: FirstViewModel, data: FirstModel) {
        TitleLabel.text = viewModel.name
    }

    func showDetail(viewModel: ViewModel) {
        router?.navToDetails(data: viewModel)
    }
}

// MARK: - Private Functions
extension FirstViewController {
    private func setupView() {
        interactor?.getDataFromJson()
    }
}
