//
//  AremRouter.swift
//  VIPLearning
//
//  Created by Alireza on 11/9/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol FirstRoutingLogic {
    func navToDetails(data: ViewModel)}

protocol FirstDataPassing {
    var dataStore: FirstDataStore? { get }
}

class FirstRouter: NSObject, FirstRoutingLogic, FirstDataPassing {
    private let sceneFactory: SceneFactory
    init(sceneFactory: SceneFactory , viewController: FirstViewController) {
        self.sceneFactory = sceneFactory
    }
    
    // MARK: - Properties
    weak var viewController: FirstViewController?
    var dataStore: FirstDataStore?
    
    func navToDetails(data: ViewModel) {

        let vc = sceneFactory.navToDetailsVc(data: data)
        sceneFactory.navigationController.pushViewController(vc, animated: true)
    }
    
}
