//
//  DetailPresenter.swift
//  VIPLearning
//
//  Created by Alireza on 11/10/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol DetailPresentationLogic {
    func passDataToVc(_ response: ViewModel)

}

class DetailPresenter: DetailPresentationLogic {
    // MARK: - Properties
    private weak var viewController: DetailDisplayLogic?
    init(viewController: DetailDisplayLogic) {
        self.viewController = viewController
    }
    func passDataToVc(_ response: ViewModel) {
        let viewModel = DetailModels.PersonData.ViewModel(name: response.name, gender: response.gender, house: response.house, birth: response.birth, year: response.year, alive: response.alive.description)
        viewController?.setupVcFromPresenter(viewModel)
    }
}
