//
//  DetailModels.swift
//  VIPLearning
//
//  Created by Alireza on 11/10/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

enum DetailModels {
    // MARK: - Use Cases
    enum PersonData {
        struct Request {}
        typealias Response = AremModel
        struct ViewModel {
            var name: String
            var gender: String
            var house: String
            var birth: String
            var year: String
            var alive: String
        }
    }
}
