//
//  DetailConfigurator.swift
//  VIPLearning
//
//  Created by Alireza on 11/10/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol DetailConfigurator {
    func configure() -> DetailViewController
}

final class DetailDefaultConfigurator {
    private var sceneFactory: SceneFactory
    private var service: NetworkProtocol
    private var data: ViewModel
    init(sceneFactory: SceneFactory, service: NetworkProtocol, data: ViewModel) {
        self.sceneFactory = sceneFactory
        self.service = service
        self.data = data
    }
}

extension DetailDefaultConfigurator: DetailConfigurator {
    @discardableResult
    func configure() -> DetailViewController {
        
        let viewController = UIStoryboard(name: "Detail", bundle: nil).instantiateViewController(withIdentifier: "DetailViewController") as! DetailViewController

        let worker = DetailWorker(service: service)
        let interactor = DetailInteractor(data: data)
        let presenter = DetailPresenter(viewController: viewController)
        let router = DetailRouter(sceneFactory: sceneFactory, viewController: viewController)

        router.dataStore = interactor
        interactor.presenter = presenter
        interactor.worker = worker
        viewController.interactor = interactor
        viewController.router = router
        
        return viewController
    }
}
