//
//  DetailInteractor.swift
//  VIPLearning
//
//  Created by Alireza on 11/10/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol DetailBusinessLogic {
    func passDataToPresenter()}

protocol DetailDataStore {
    
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    // MARK: - Properties
    var presenter: DetailPresentationLogic?
    var worker: DetailWorkerLogic?
    private var data: ViewModel
    init(data: ViewModel) {
        self.data = data
    }
    
    func passDataToPresenter() {
        presenter?.passDataToVc(data)
    }

}
