//
//  DetailViewController.swift
//  VIPLearning
//
//  Created by Alireza on 11/10/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol DetailDisplayLogic: AnyObject {
    func setupVcFromPresenter(_ viewModel: DetailModels.PersonData.ViewModel)
}

class DetailViewController: UIViewController {
    
    var interactor: (DetailBusinessLogic & DetailDataStore)?
    var router: DetailRoutingLogic?
    
    @IBOutlet weak var aliveLabel: UILabel!
    @IBOutlet weak var yearLabel: UILabel!
    @IBOutlet weak var birthDateLabel: UILabel!
    @IBOutlet weak var houseLabel: UILabel!
    @IBOutlet weak var genderLabel: UILabel!
    @IBOutlet weak var nameLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.passDataToPresenter()
    }
    
}

// MARK: - Display Logic Functions
extension DetailViewController: DetailDisplayLogic {
    
    func setupVcFromPresenter(_ viewModel: DetailModels.PersonData.ViewModel) {
//                data.alive ? (aliveLabel.text = "Yes") : (aliveLabel.text = "No")
        yearLabel.text = viewModel.year
        birthDateLabel.text = viewModel.birth
        houseLabel.text = viewModel.house
        genderLabel.text = viewModel.gender
        nameLabel.text = viewModel.name
    }
}

// MARK: - Private Functions
extension DetailViewController {

    
}
