//
//  DetailWorker.swift
//  VIPLearning
//
//  Created by Alireza on 11/10/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol DetailWorkerLogic {
    
}

class DetailWorker: DetailWorkerLogic {
     let service: NetworkProtocol
    
     init(service: NetworkProtocol) {
         self.service = service
     }

    // MARK: - Methods

}
