//
//  AremPresenter.swift
//  VIPLearning
//
//  Created by Alireza on 11/9/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol AremPresentationLogic {
    func getPersonName(data: aremDatas, index: Int)
    func getPersonData(data: aremDatas, index: Int) 
}

class AremPresenter: AremPresentationLogic {
    // MARK: - Properties
    private weak var viewController: (AremDisplayLogic)?
    init(viewController: AremDisplayLogic) {
        self.viewController = viewController
    }
    
    func getPersonName(data: aremDatas, index: Int) {
        let viewModel: AremViewModel = AremViewModel(name: data[index].name)
        viewController?.showNextName(viewModel: viewModel, data: data[index])
    }
    
    func getPersonData(data: aremDatas, index: Int) {
        let person = data[index]
        let viewModel: ViewModel = ViewModel(name:person.name , gender: person.gender.rawValue, house: person.house.rawValue, birth: person.house.rawValue, year: person.yearOfBirth?.description ?? "", alive: person.alive)
        viewController?.showDetail(viewModel: viewModel)
    }
}

struct AremViewModel {
    var name: String
}

struct ViewModel {
    var name: String
    var gender: String
    var house: String
    var birth: String
    var year: String
    var alive: Bool
}
