//
//  AremViewController.swift
//  VIPLearning
//
//  Created by Alireza on 11/9/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol AremDisplayLogic: AnyObject {
    func showNextName(viewModel: AremViewModel, data: AremModel)
    func showDetail(viewModel: ViewModel)
}

class AremViewController: UIViewController {
    var interactor: (AremBusinessLogic & AremDataStore)?
    var router: AremRoutingLogic?
        
    @IBOutlet weak var detailButton: UIButton!
    @IBOutlet weak var actButton: UIButton!
    @IBOutlet weak var TitleLabel: UILabel!
    @IBAction func actButonAction(_ sender: Any) {
       interactor?.getDataFromJson()
    }
    
    @IBAction func detailButtonAction(_ sender: Any) {
        interactor?.getRoutingData()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupView()
    }
}

// MARK: - Display Logic Functions
extension AremViewController: AremDisplayLogic {
    func showNextName(viewModel: AremViewModel, data: AremModel) {
        TitleLabel.text = viewModel.name
    }

    func showDetail(viewModel: ViewModel) {
        router?.navToDetails(data: viewModel)
    }
}

// MARK: - Private Functions
extension AremViewController {
    private func setupView() {
        interactor?.getDataFromJson()
    }
}
