//
//  AremInteractor.swift
//  VIPLearning
//
//  Created by Alireza on 11/9/1401 AP.
//  Copyright © 1401 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol AremBusinessLogic {

}

protocol AremDataStore {
    func getDataFromJson()
    func getRoutingData()
}

class AremInteractor {
    // MARK: - Properties
    var presenter: AremPresentationLogic?
    var worker: AremWorkerLogic?
    
    private var index = -1

    func addIndexValue(dataCount: Int){
        if index != dataCount {
            index += 1
        } else {
            index = 0
        }
    }
}

extension AremInteractor: AremBusinessLogic, AremDataStore {
    
    func getDataFromJson(){
        guard let data = worker?.getData() else { fatalError("No data")}
        addIndexValue(dataCount: data.count)
        presenter?.getPersonName(data: data, index: index)
    }
    
    func getRoutingData(){
//        completion
        guard let data = worker?.getData() else { fatalError("No data")}
        presenter?.getPersonData(data: data, index: index)
    }
    
}
